name: Docker Image Build & Push

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin


     - name: Build and push Docker image
        run: |
            docker build -t anujprakashdixit/fastapi-docker:latest .
            docker push anujprakashdixit/fastapi-docker:latest

